function cfg = cl_pulv_bodysignals_bacchus_visualization_settings(experiment_id)
%CL_PULV_BODYSIGNALS_BACCHUS_VISUALIZATION_SETTINGS  Plot defaults for Bacchus (B).
%
% Paired with cl_pulv_bodysignals_bacchus_penetration_db.m (auto-discovered).
% Optional: cfg.plot_opts.Zoom = 2;  % central 50% crop on slice plots

cfg = struct( ...
    'marker_style', struct( ...
        'FaceColor', [1 0 0], ...
        'EdgeColor', [1 0 0], ...
        'FaceAlpha', 0.3, ...
        'EdgeAlpha', 1, ...
        'MarkerSize', 3, ...
        'LineWidth', 0.25), ...
    'plot_opts', struct( ...
        'JitterFraction', 0.75, ...
        'DrawTrajectory', true, ...
        'Zoom', 4), ...
    'category_colors', {{[1 0 0]}});

switch experiment_id
    case 'Pulv_bodysignals_VP_R'       % 18 sites
    case 'Pulv_bodysignals_dPul_L'     % 116 sites
    case 'Pulv_bodysignals_dPul_R'     % 28 sites
    case 'Pulv_bodysignals_MD_L'       % 6 sites, single hole
    case 'Pulv_bodysignals_MD_R'       % 56 sites
    otherwise
        error('Unknown experiment_id: %s', experiment_id);
end

end
