function cfg = cl_pulv_bodysignals_magnus_visualization_settings(experiment_id)
%CL_PULV_BODYSIGNALS_MAGNUS_VISUALIZATION_SETTINGS  Plot defaults for Magnus (M).
%
% Paired with cl_pulv_bodysignals_magnus_penetration_db.m (auto-discovered).

cfg = struct( ...
    'marker_style', struct( ...
        'FaceColor', [1 0 0], ...
        'EdgeColor', [1 0 0], ...
        'FaceAlpha', 0.3, ...
        'EdgeAlpha', 1, ...
        'MarkerSize', 3), ...
        cfg.plot_opts = struct( ...
        'JitterFraction', 1, ...
        'DrawTrajectory', true), ...
        cfg.category_colors = {{[1 0 0]}};

switch experiment_id
    case 'Pulv_bodysignals_VP_L'       % 180 sites
    case 'Pulv_bodysignals_dPul_L'     % 127 sites
    case 'Pulv_bodysignals_dPul_R'     % 311 sites — dense
    case 'Pulv_bodysignals_MD_L'       % 154 sites
    otherwise
        error('Unknown experiment_id: %s', experiment_id);
end

end
